sleep_time: 1m # Sleep time between each check
log_level: info
clients:
  - name: radarr
    host: http://example.com
    api_key: ....
    conditions:
      waiting_threshold: 10m # How long should wait for torrent before checking the status
      download_timeout_threshold: 24h
      average_speed_threshold: 256000 # Bytes -> 200KB/s
    options:
      blocklist: true
  - name: sonarr
    host: http://example.com
    api_key: ...
    conditions:
      waiting_threshold: 10m
      download_timeout_threshold: 48h
      average_speed_threshold: 256000 # 200KB/s
    options:
      blocklist: true # Blocklist the torrent on deletion to prevent re-downloading the same torrent